---
# Factorio Dedicated Server GameDefinition
# Factorio is a game about building and creating automated factories to produce items of increasing complexity.

apiVersion: boilerr.dev/v1alpha1
kind: GameDefinition
metadata:
  name: factorio
  labels:
    boilerr.io/game-genre: automation
    boilerr.io/multiplayer: coop

spec:
  # Note: Factorio doesn't use SteamCMD, requires custom image with Factorio headless
  # App ID reference (for documentation): Factorio doesn't have a SteamCMD app ID
  # Using factoriotools/factorio or similar community image
  appId: 427520  # Factorio game App ID (not used by SteamCMD but for reference)

  # Override with Factorio-specific image
  image: factoriotools/factorio:stable

  # Factorio installs to /factorio in the community image
  installDir: /factorio

  # Command to start Factorio server
  # The --start-server-load-latest loads the most recent save
  command: /factorio/bin/x64/factorio

  args:
    - --start-server-load-latest
    - --server-settings
    - /factorio/config/server-settings.json
    - --server-adminlist
    - /factorio/config/server-adminlist.json
    - --server-whitelist
    - /factorio/config/server-whitelist.json
    - --server-banlist
    - /factorio/config/server-banlist.json
    # Bind to all interfaces
    - --bind
    - 0.0.0.0:{{.Config.port}}
    # RCON configuration
    - --rcon-port
    - "{{.Config.rconPort}}"
    - --rcon-password
    - "{{.Config.rconPassword}}"

  # Factorio uses UDP for game traffic, TCP for RCON
  ports:
    - name: game
      containerPort: 34197
      protocol: UDP
    - name: rcon
      containerPort: 27015
      protocol: TCP

  # Factorio environment variables
  env:
    # Update mods on startup
    - name: UPDATE_MODS_ON_START
      value: "{{.Config.updateMods}}"
    # Load latest save on startup
    - name: LOAD_LATEST_SAVE
      value: "true"

  configSchema:
    # Server identity
    serverName:
      description: "Server name displayed in the server browser"
      default: "Factorio Server"
      required: true

    description:
      description: "Server description shown in browser"
      default: "A Factorio server managed by Boilerr"

    # Network settings
    port:
      description: "Game port (UDP)"
      default: "34197"

    maxPlayers:
      description: "Maximum number of players (0 = unlimited)"
      default: "0"

    # Visibility
    visibility:
      description: "Server visibility (public, lan, steam)"
      default: "public"
      enum: ["public", "lan", "steam"]

    # Authentication
    requireUserVerification:
      description: "Require players to log in to factorio.com"
      default: "true"
      enum: ["true", "false"]

    password:
      description: "Server password (leave empty for no password)"
      secret: true

    # Game settings
    gameName:
      description: "Name of the save file"
      default: "default"

    # Autosave settings
    autosaveInterval:
      description: "Autosave interval in minutes"
      default: "5"

    autosaveSlots:
      description: "Number of autosave slots to keep"
      default: "3"

    # AFK settings
    afkAutokickInterval:
      description: "Minutes before AFK players are kicked (0 = disabled)"
      default: "0"

    # PvP settings
    allowCommands:
      description: "Allow players to use console commands (admins only recommended)"
      default: "admins-only"
      enum: ["true", "false", "admins-only"]

    # Mod settings
    updateMods:
      description: "Automatically update mods on server start"
      default: "false"
      enum: ["true", "false"]

    # RCON settings
    rconPort:
      description: "RCON port (TCP)"
      default: "27015"

    rconPassword:
      description: "RCON password for remote administration"
      secret: true
      required: true

    # Admin list
    admins:
      description: "List of admin usernames (Factorio.com usernames, comma-separated)"
      array: true

    # Whitelist
    whitelist:
      description: "List of whitelisted usernames (empty = no whitelist, comma-separated)"
      array: true

    # Banlist
    banned:
      description: "List of banned usernames (comma-separated)"
      array: true

  # Server configuration files
  configFiles:
    - path: /factorio/config/server-settings.json
      content: |
        {
          "name": "{{.Config.serverName}}",
          "description": "{{.Config.description}}",
          "tags": ["game", "tags"],
          "_comment_max_players": "Maximum number of players allowed, admins can join even a full server. 0 means unlimited.",
          "max_players": {{.Config.maxPlayers}},
          "_comment_visibility": "public: Game will be published on the official Factorio matching server",
          "visibility": {
            "public": {{if eq .Config.visibility "public"}}true{{else}}false{{end}},
            "lan": {{if eq .Config.visibility "lan"}}true{{else}}false{{end}},
            "steam": {{if eq .Config.visibility "steam"}}true{{else}}false{{end}}
          },
          "_comment_credentials": "Your factorio.com login credentials. Required for games with visibility public",
          "username": "",
          "password": "",
          "_comment_token": "Authentication token. May be used instead of 'password' above.",
          "token": "",
          "game_password": "{{.Config.password}}",
          "_comment_require_user_verification": "When set to true, the server will only allow clients that have a valid Factorio.com account",
          "require_user_verification": {{.Config.requireUserVerification}},
          "_comment_max_upload_in_kilobytes_per_second": "optional, default value is 0. 0 means unlimited.",
          "max_upload_in_kilobytes_per_second": 0,
          "_comment_max_upload_slots": "optional, default value is 5. 0 means unlimited.",
          "max_upload_slots": 5,
          "_comment_minimum_latency_in_ticks": "optional one tick is ~16ms in default speed, default value is 0. 0 means no minimum.",
          "minimum_latency_in_ticks": 0,
          "_comment_ignore_player_limit_for_returning_players": "Players that played on this map already can join even when the max player limit was reached.",
          "ignore_player_limit_for_returning_players": false,
          "_comment_allow_commands": "possible values are, true, false and admins-only",
          "allow_commands": "{{.Config.allowCommands}}",
          "_comment_autosave_interval": "Autosave interval in minutes",
          "autosave_interval": {{.Config.autosaveInterval}},
          "_comment_autosave_slots": "server autosave slots, it is cycled through when the server autosaves.",
          "autosave_slots": {{.Config.autosaveSlots}},
          "_comment_afk_autokick_interval": "How many minutes until someone is kicked when doing nothing, 0 for never.",
          "afk_autokick_interval": {{.Config.afkAutokickInterval}},
          "_comment_auto_pause": "Whether should the server be paused when no players are present.",
          "auto_pause": true,
          "only_admins_can_pause_the_game": true,
          "_comment_autosave_only_on_server": "Whether autosaves should be saved only on server or also on all connected clients. Default is true.",
          "autosave_only_on_server": true,
          "_comment_non_blocking_saving": "Highly experimental feature, enable only at your own risk of losing your saves. On UNIX systems, server will fork itself to create an autosave. Autosaving on connected Windows clients will be disabled regardless of autosave_only_on_server option.",
          "non_blocking_saving": false,
          "_comment_minimum_segment_size": "Long network messages are split into segments that are sent over multiple ticks. Their size depends on the number of peers currently connected. Increasing the segment size will increase upload bandwidth requirement for the server and download bandwidth requirement for clients. This setting only affects server outbound messages. Changing these settings can have a negative impact on connection stability for some clients.",
          "minimum_segment_size": 25,
          "minimum_segment_size_peer_count": 20,
          "maximum_segment_size": 100,
          "maximum_segment_size_peer_count": 10
        }

    - path: /factorio/config/server-adminlist.json
      content: |
        [
          {{range $i, $admin := split .Config.admins ","}}{{if $i}},{{end}}
          "{{$admin}}"{{end}}
        ]

    - path: /factorio/config/server-whitelist.json
      content: |
        [
          {{range $i, $user := split .Config.whitelist ","}}{{if $i}},{{end}}
          "{{$user}}"{{end}}
        ]

    - path: /factorio/config/server-banlist.json
      content: |
        [
          {{range $i, $user := split .Config.banned ","}}{{if $i}},{{end}}
          "{{$user}}"{{end}}
        ]

  # Factorio can be resource-intensive with large factories
  defaultResources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # Save files can grow large, especially with mods
  defaultStorage: "10Gi"

  # Health check - Factorio accepts TCP connections on RCON port
  healthCheck:
    tcpSocket:
      port: rcon
    # Factorio starts relatively quickly
    initialDelaySeconds: 60
    periodSeconds: 30

---
# Example SteamServer for Factorio
# Users create this to deploy their server instance
apiVersion: boilerr.dev/v1alpha1
kind: SteamServer
metadata:
  name: my-factorio-server
  namespace: games
spec:
  gameDefinition: factorio

  config:
    serverName: "Factory Must Grow"

    description: "A friendly Factorio server for automation enthusiasts"

    gameName: "default"

    maxPlayers: "10"

    visibility: "public"

    requireUserVerification: "true"

    password:
      secretKeyRef:
        name: factorio-secrets
        key: server-password

    rconPassword:
      secretKeyRef:
        name: factorio-secrets
        key: rcon-password

    allowCommands: "admins-only"

    autosaveInterval: "10"

    autosaveSlots: "5"

    updateMods: "false"

    admins: "admin1,admin2"

  storage:
    size: 20Gi
    storageClassName: nfs-client

  serviceType: LoadBalancer
